version: 2
jobs:
  test:
    docker:
      - image: "circleci/node:9.6.1"
    working_directory: ~/CashGraph
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .BuildNum }}
            - v1-dependencies-
      - run: 
          name: Install dependencies
          command: 'cd client && npm install'
      - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ .BuildNum }}
      - run:
          name: Run client tests
          command: 'cd client && npm run test'
workflows:
  version: 2
  test:
    jobs:
      - test
